#!/usr/bin/env python3
"""Generate the feature menu from the shared registry; --check is read-only."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def render():
    features=json.loads((ROOT/'data/publishing.json').read_text())['features']
    lines=['# Feature menu', '', f'The registry defines **{len(features)} feature flags**. This table is generated by `scripts/feature_docs.py`.', '',
           'Set a flag in the selected TOML configuration. A disabled dependency also disables its dependent feature. For example, `about = false` makes `team` inactive even if its flag remains true.', '',
           'A deselected feature whose page is still published renders as a neutral noindex shell: body, structured data, and social image suppressed, excluded from search and sitemap, and inline Markdown links to it render as text. In this site every deselected page is also `draft: true`, so those routes are not generated at all and return 404. Restoring one means clearing both the draft flag and the feature flag.', '',
           'This site builds with `hugo.toml,profiles/jeff-does-doors.toml,hugo-staging.toml` for review and `hugo.toml,profiles/jeff-does-doors.toml,hugo-launch.toml` for the launch selection. Both are checked against this registry. See [owner inputs](launch-inputs.md).', '',
           '| Flag | Purpose / use when | Inputs before publication | Requires |', '| --- | --- | --- | --- |']
    for name,f in features.items():
        lines.append(f'| `{name}` | {f["label"]}: {f["useWhen"]} | {f["inputs"]} | '+(', '.join(f['requires']) or '—')+' |')
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'docs/chisel-menu.md';text=render()
    if args.check:
        raise SystemExit(0 if path.read_text()==text else 'Feature menu is stale; run python3 scripts/feature_docs.py')
    path.write_text(text)
